[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = 'source $HOME/.vim/rc/plugins/neocomplete.rc.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source $HOME/.vim/rc/plugins/denite.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = 'vim-airline/vim-airline-themes'
hook_add = 'source $HOME/.vim/rc/plugins/vim-airline.rc.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/tComment'

[[plugins]]
repo = 'Raimondi/delimitMate'

# [[plugins]]
# repo = 'myusuf3/numbers.vim'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = 'source ~/.vim/rc/plugins/tagbar.rc.vim'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'rking/ag.vim'
on_cmd = ['Ag']
hook_add = '''
let g:ackprg='ag --nogroup --nocolor --column'
'''

[[plugins]]
repo = 'petRUShka/vim-sage'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
colorscheme gruvbox
let g:gruvbox_constrast='soft'
set termguicolors
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters_explicit = 1
let g:ale_linters = {
\  'cpp': ['cppcheck'],
\ }
'''
