[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree']
hook_add = '''
nnoremap <silent> <leader>d :<C-u>NERDTree<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") |q| endif
'''

[[plugins]]
repo = 'LaTex-Box-Team/LaTex-Box'
on_ft = ['tex']
hook_add = 'source $HOME/.vim/rc/plugins/latex-box.rc.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['cpp', 'c', 'java']
hook_add = 'source $HOME/.vim/rc/plugins/syntastic.rc.vim'

[[plugins]]
repo = 'neomake/neomake'
on_ft = ['cpp', 'c', 'java', 'py']
hook_add = 'source $HOME/.vim/rc/plugins/neomake.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
on_ft = ['cpp', 'c', 'java', 'py', 'tex']
hook_add = 'source $HOME/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_ft = ['cpp', 'c', 'java', 'py', 'tex']

[[plugins]]
repo = 'ivanov/vim-ipython'
on_ft = ['py']

[[plugins]]
repo = 'kiteco/vim-plugin'
on_ft = ['py']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = 'Shougo/vimproc.vim'
on_cmd = ['VimShell']

