[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree']
hook_add = '''
nnoremap <silent> <leader>d :<C-u>NERDTree<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") |q| endif
'''

[[plugins]]
repo = 'Rip-Rip/clang_complete'
on_ft = ['cpp', 'c']
hook_add = 'source $HOME/.vim/rc/plugins/clang_complete.rc.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
hook_add = '''
let g:jedi#popup_on_dot = 0
let g:jedi#completions_command ="<C-N>"
'''

[[plugins]]
repo = 'LaTex-Box-Team/LaTex-Box'
on_ft = ['tex']
hook_add = 'source $HOME/.vim/rc/plugins/latex-box.rc.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
on_hook = '''
let g:go_fmt_fail_silently = 1
let g:go_fmt_commond = 'goimports'
'''

[[plugins]]
repo = 'Blackrush/vim-gocode'
on_ft = ['go']

[[plugins]]
repo = 'dgryski/vim-godef'
on_ft = ['go']

# [[plugins]]
# repo = 'scrooloose/syntastic'
# on_ft = ['cpp', 'c', 'java', 'py']
# hook_add = 'source $HOME/.vim/rc/plugins/syntastic.rc.vim'

[[plugins]]
repo = 'neomake/neomake'
on_ft = ['cpp', 'c', 'java', 'py']
hook_add = 'source $HOME/.vim/rc/plugins/neomake.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
on_ft = ['cpp', 'c', 'java', 'py', 'tex']
hook_add = 'source $HOME/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_ft = ['cpp', 'c', 'java', 'py', 'tex']

[[plugins]]
repo = 'ivanov/vim-ipython'
on_ft = ['py']

[[plugins]]
repo = 'kiteco/vim-plugin'
on_ft = ['py']
