if $SHELL =~ 'fish'
    set shell=/bin/bash
endif
let mapleader = "\<Space>"
set nocompatible
filetype off
" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

if &compatible
    set nocompatible
endif

" Required:
let s:dein_dir = expand('~/.cache/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

if dein#load_state(s:dein_dir)
    call dein#begin(s:dein_dir)
    let g:rc_dir = expand('~/.vim/rc')
    let s:toml = g:rc_dir . '/dein.toml'
    let s:lazy_toml = g:rc_dir . '/dein_lazy.toml'

    call dein#load_toml(s:toml, {'lazy' : 0})
    call dein#load_toml(s:lazy_toml, {'lazy' : 1})
    call dein#end()
    call dein#save_state()
endif

filetype plugin indent on
syntax enable
" If you want to install not installed plugins on startup.
if dein#check_install()
    call dein#install()
endif

" Basic Settings
set nocp ""set no compatiable
set ru   ""set ruler
set hls  ""set hightlights
set backspace=indent,eol,start  ""backspace will take care of indent EOF etc.
set whichwrap=b,s,<,>,[,]
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936
set number
set showcmd
set t_Co=256
set nocursorcolumn
set nocursorline
set norelativenumber
set foldmethod=indent
set nofoldenable
set smartcase
set matchtime=1 "100MS
set showtabline=1
set incsearch
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P
syntax sync minlines=80 maxlines=300
set synmaxcol=128
set regexpengine=1
set lazyredraw
inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>0
xnoremap * :<C-u>call <SID>VSetSearch()<CR>/<C-R>=@/<CR><CR>
xnoremap # :<C-u>call <SID>VSetSearch()<CR>?<C-R>=@/<CR><CR>
function! s:VSetSearch()
    let temp = @s
    norm! gv"sy
    let @/ = '\V' . substitute(escape(@s, '/\'), '\n', '\\n', 'g')
    let @s = temp
endfunction

set expandtab
set sw=4  ""auto indent for 4
set ts=4  ""tab width for 4
set smarttab  ""can delete four space at once.
set sm  ""parentless match
set cindent ""C Indent
set cino+=N-s,g0,:0,(0
set selection=inclusive
:map <bs> bdw
"set background=dark
colorscheme solarized
