if $SHELL =~ 'fish'
    set shell=/bin/bash
endif
let mapleader = ","
set nocompatible
filetype off
" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

if has('vim_starting')
    set nocompatible               " Be iMproved
    " Required:
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'
call neobundle#begin('~/.vim/bundle/')

NeoBundle 'Shougo/neobundle.vim'

NeoBundle 'Shougo/unite.vim'

NeoBundle 'bling/vim-airline'

NeoBundleLazy 'scrooloose/nerdtree', {
            \ 'autoload' : {'commands' : ['NERDTree']}
            \}

NeoBundleLazy 'davidhalter/jedi-vim', {
            \ 'autoload' : {'filetypes' : ["python"]}
            \}

NeoBundle 'majutsushi/tagbar'

NeoBundle "kien/rainbow_parentheses.vim"

autocmd BufRead *.sage set filetype=python

if has("mac")
NeoBundleLazy 'rip-rip/clang_complete', {
            \ 'autoload': {'filetypes': ["cpp", "c"]}
            \ }
NeoBundleLazy 'Shougo/neocomplcache-clang_complete', {
			\ 'autoload': {'filetypes': ["cpp", "c"]}
			\}
endif

NeoBundle 'vim-scripts/google.vim'

NeoBundleLazy 'Shougo/neocomplete', {
            \ 'autoload' : { 'insert' : '1'}
			\ }
NeoBundle 'tpope/vim-surround'

NeoBundle 'tpope/vim-fugitive'

NeoBundle 'scrooloose/syntastic'

NeoBundleLazy 'rking/ag.vim', {
            \'autoload' : { 'commands' : ["Ag"] }
            \}

NeoBundle 'tpope/vim-commentary'

NeoBundle 'Shougo/neosnippet'

NeoBundle 'Shougo/neosnippet-snippets'

NeoBundle 'Raimondi/delimitMate'

NeoBundle "myusuf3/numbers.vim"

NeoBundle 'terryma/vim-multiple-cursors'

NeoBundleLazy 'fatih/vim-go', {
            \ 'autoload' : {'filetypes' : ['go']}
            \ }

let g:go_fmt_command = 'goimports'

NeoBundleLazy 'Blackrush/vim-gocode', {
            \ 'autoload' : {'filetypes' : ['go']}
            \}

NeoBundleLazy 'dgryski/vim-godef', {
            \ 'autoload' : {'filetypes' : ['go']}
            \}

NeoBundleLazy 'peterhoeg/vim-qml', {
            \ 'autoload' : {'filetypes' : ['qml']}
            \}

NeoBundle 'Shougo/vimproc.vim', {
            \ 'build' : {
            \ 'mac' : 'make -f make_mac.mak'}}

NeoBundle 'Shougo/vimshell'

call neobundle#end()
NeoBundleCheck

" Basic Settings
set nocp ""set no compatiable
set ru   ""set ruler
set hls  ""set hightlights
set backspace=indent,eol,start  ""backspace will take care of indent EOF etc.
set whichwrap=b,s,<,>,[,]
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936
set number
set showcmd
set t_Co=256
"set foldmethod=indent
set smartcase
set matchtime=1 "100MS
set showtabline=1
set incsearch
nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>
syntax on
filetype indent on
inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>0
xnoremap * :<C-u>call <SID>VSetSearch()<CR>/<C-R>=@/<CR><CR>
xnoremap # :<C-u>call <SID>VSetSearch()<CR>?<C-R>=@/<CR><CR>
function! s:VSetSearch()
    let temp = @s
    norm! gv"sy
    let @/ = '\V' . substitute(escape(@s, '/\'), '\n', '\\n', 'g')
    let @s = temp
endfunction

set sw=4  ""auto indent for 4
set ts=4  ""tab width for 4
set smarttab  ""can delete four space at once.
set sm  ""parentless match
"set cin ""C Indent
autocmd BufWritePre * :%s/\s\+$//e "auto strip trailling whitespace
set selection=inclusive

set background=light
" set tw=78 fo+=Mm
" set cc=80
colorscheme solarized
